"""Manual-oriented intermediate representations."""

from .builder import ManualIRBuildOptions, build_manual_ir
from .context_pack import build_context_pack, write_context_pack
from .models import (
    BackpressureBehavior,
    BackpressurePoint,
    BoundaryInterface,
    ArtifactTarget,
    ChannelCard,
    ChannelConditioning,
    ChannelEndpoint,
    ChannelPayload,
    ComponentContract,
    ComponentRoleRef,
    CoveragePriority,
    ExternalDependencyRef,
    FlowBlockingPoint,
    FlowDecisionPoint,
    FlowPath,
    FlowStep,
    GeneratedFrom,
    HandshakeRule,
    KeyComponentRole,
    KeyInterfaces,
    ManualIR,
    ManualIRIndexes,
    ManualIRObject,
    ManualIRObjects,
    ModuleCard,
    ModuleRoleRef,
    ReadingPath,
    ReadingSection,
    ReleaseRule,
    RoleMapping,
    SemanticContract,
    SignalEndpoint,
    SourceRef,
    SystemView,
)
from .split_store import build_object_catalog, list_reading_paths, resolve_manual_ir_object, resolve_manual_ir_objects
from .validator import validate_manual_ir_split

__all__ = [
    "BackpressureBehavior",
    "BackpressurePoint",
    "BoundaryInterface",
    "ArtifactTarget",
    "ChannelCard",
    "ChannelConditioning",
    "ChannelEndpoint",
    "ChannelPayload",
    "ManualIRBuildOptions",
    "ComponentContract",
    "ComponentRoleRef",
    "CoveragePriority",
    "ExternalDependencyRef",
    "FlowBlockingPoint",
    "FlowDecisionPoint",
    "FlowPath",
    "FlowStep",
    "GeneratedFrom",
    "HandshakeRule",
    "KeyComponentRole",
    "KeyInterfaces",
    "ManualIR",
    "ManualIRIndexes",
    "ManualIRObject",
    "ManualIRObjects",
    "ModuleCard",
    "ModuleRoleRef",
    "ReadingPath",
    "ReadingSection",
    "ReleaseRule",
    "RoleMapping",
    "SemanticContract",
    "SignalEndpoint",
    "SourceRef",
    "SystemView",
    "build_manual_ir",
    "build_context_pack",
    "build_object_catalog",
    "list_reading_paths",
    "resolve_manual_ir_object",
    "resolve_manual_ir_objects",
    "validate_manual_ir_split",
    "write_context_pack",
]
