// Interrupt Enable and Priority Encoder
// Copyright Mentor Graphics Corporation and Licensors 2001

// This module provides the interrupt enable register and priority encoding
// for the M16550s UART.

// Revision history:
//
// $Log: m3s004fd.v,v $
// Revision 1.4  2004/12/10
// ECN02360 rtl update
//
// Revision 1.3  2001/03/21
// Added CVS log tag
// Removed old Change history associated with version 8.8 ofthe m16550a core
//

module m3s004fd (
  CLOCK, RESETN, WrCyc, RdCyc, ADD0, ADD1, ADD2,
  DataIn, DR, BI, FE, PE, OE, RTO,
  DDCD, TERI, DDSR, DCTS, THRe,
  LoadTxBuff, FIFOE,
  DMA, TFull, RHold1, RxAboveTrig,
  TSRE, TEmpt, Delta_TRST, RRST,
  IRQ, IIR, IER, TXRdy, RXRdy
  );


input       CLOCK, RESETN, WrCyc, RdCyc, ADD0, ADD1, ADD2;
input [3:0] DataIn;
input       DR, BI, FE, PE, OE, RTO; 
input       DDCD, TERI, DDSR, DCTS, THRe;
input       LoadTxBuff, FIFOE;
input       DMA, TFull, RHold1;
input       RxAboveTrig;
input       TSRE, TEmpt, Delta_TRST, RRST;

output [3:0] IIR, IER;
output       IRQ, TXRdy, RXRdy;


reg [3:0] IIR, IER;
reg       IRQ, EnabRxBuff, EnabTxBuff, EnabLnStat, EnabMdStat;
reg       THRemA, THRemB, THRemC, THRemD, THRemE, THRemF;
reg       DREmptyA, DREmptyB;
reg       TXRdy, RXRdy;
reg       RHold, THold;
reg       DMA0_SEL, DMA0_TXRdy;
reg       FIFOE_DEL, Delta_FIFOE;
reg       DMA0_TXRdySamp;
reg       Delta_DMA0_TXRdy;
reg       RTOSync, TriggerSync;
reg       THRem1, THRem2, THRemI, TxIntRd, TxIntRdLtch;
reg       Trigger, DREmpty;
reg       Prior1, Prior2, Prior2TO, Prior3, Prior4;
reg       RTO_Pulse, Trigger_Pulse;

// Interrupt enable register
always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    IER <= 4'b0000;
  else
    if (WrCyc & ADD1) IER <= DataIn[3:0];

// Assign interrupt enables
always @(IER)
begin
  EnabRxBuff = IER[0];
  EnabTxBuff = IER[1];
  EnabLnStat = IER[2];
  EnabMdStat = IER[3];
end

// Signal HOLD indicates TX fifo will be emptied on next read
// or RBR will be emptied on next read
// Used for THRe INTR
always @(FIFOE)
  THold = ~FIFOE;

// Signal HOLD indicates RX fifo will be emptied on next read
// or RBR will be emptied on next read
// Used by RXRdy pin
always @(FIFOE or RHold1)
  if (FIFOE)
    RHold = RHold1;
  else
    RHold = 1'b0;


// Generate a delta version of FIFOE, since this will generate a TX interrupt
// because FIFOE changing resets FIFO and makes it go empty
always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    FIFOE_DEL <= 1'b0;
  else
    FIFOE_DEL <= FIFOE;

always @ (FIFOE_DEL or FIFOE)
  Delta_FIFOE = FIFOE ^ FIFOE_DEL;


// Explanation for Interrupt Scheme
//
// This section generates the Transmit Holding Register Empty (THRe) Interrupt.
// The interrupt is made up from the FIFO THRe Interrupt (TFEI) and the 450 Mode THRe Interrupt (THRemI)
//
// Generating (TFEI):
//
// A Transmit FIFO Empty Interrupt is generated by any one of the following occuring:
// 	1) The Transmitter FIFO emptys itself (Rising edge on DMA0_TXRdy) 
//	and the FIFO is enabled (FIFOE = '1')
//	2) The FIFO is enabled, if it had been disabled before (Rising edge on FIFOE), 
//	3) The THRe interrupt is enabled, even if it was already enabled,
//	the FIFO is enabled (FIFOE = '1') and the Transmitter FIFO is empty (DMA0_TXRdy = '1')
//	4) The Transmit FIFO is reset.
//
// The interrupt is cleared by any of the following occuring:
//	1) The Transmit Holding Register is written to.
//	2) The Interrupt Ident Register is Read. 
//
// The interrupt is gated on and off with:
//	1) The THRe Interrupt bit in the Interrrupt Enable Register (EnabTxBuff ='1/0')
//
//
// Generating (THRemI):
//
// A Transmit Holding Register Empty Interrupt is generated by any one of the following occuring:
//	1) The THRe interrupt is enabled, even if it was already enabled,
//	the FIFO is disabled and the THR is empty (THRe = '1')
//	2) The last character in the THR starts to be transmitted (rising edge of LoadTxBuff) and
//	the FIFO is disabled.
//	3) The FIFO is disabled if it had been enabled before.
//
// The interrupt is cleared by any of the following occuring:
//	1) The Transmit Holding Register is written to.
//	2) The Interrupt Ident Regsiter is Read. 
//
// The interrupt is gated on and off with:
//	1) the THRe Interrupt bit in the Interrrupt Enable Register (EnabTxBuff ='1/0')


// Transmit Holding Register Empty Interrupt generation

// Detect read of Tx interrupt
always @(ADD2 or RdCyc or IIR)
  TxIntRd = RdCyc & ADD2 & ~IIR[2] & IIR[1];

always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    TxIntRdLtch <= 1'b0;
  else
    TxIntRdLtch <= TxIntRd;

// Start with Holding register empty which is cleared by a write to 
// the TX register, or a read from the IID register. It is set by a 
// write to IER if THRe = 1

always @(posedge CLOCK or negedge RESETN)
  if (~RESETN) 
    THRemA <= 1'b0;
  else if (WrCyc & ADD0 & THRem1)
    THRemA <= THRemB;          // Reset loop if THRem1 is active
  else if (WrCyc & ADD1 & DataIn[1] & THRe)
    THRemA <= ~THRemB;         // Set loop if a write to IER and THRe active

always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    THRemB <= 1'b0;
  else if (TxIntRdLtch & ~TxIntRd)  
    THRemB <= THRemA;           // Clear down THRe if a read from IIR

always @(THRemA or THRemB)
  THRem1 = THRemA ^ THRemB;


// Next source of THRe is if TX holding register becomes empty. This is
// cleared by a write to register 0 or a read from the IIR
always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    THRemC <= 1'b0;
  else if ((LoadTxBuff & THold & ~FIFOE) | (Delta_FIFOE) | 
           (Delta_TRST) | (Delta_DMA0_TXRdy & FIFOE))
    THRemC <= ~THRemD;
  else if (~THRem2)
    THRemC <= THRemD;

always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    THRemD <= 1'b0;
  else if (WrCyc & ADD0)
    THRemD <= THRemC;

always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    THRemE <= 1'b0;
  else if ((LoadTxBuff & THold & ~FIFOE) | (Delta_FIFOE) | 
           (Delta_TRST) | (Delta_DMA0_TXRdy & FIFOE))
    THRemE <= ~THRemF;
  else if (~THRem2)
    THRemE <= THRemF;

always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    THRemF <= 1'b0;
  else if (TxIntRdLtch & ~TxIntRd)
    THRemF <= THRemE;

always @(THRemC or THRemD or THRemE or THRemF)
  THRem2 = ((THRemC ^ THRemD) & (THRemE ^ THRemF));
always @(THRem1 or THRem2)
  THRemI = THRem1 | THRem2;


// Trigger level interrupt generation
always @(FIFOE or RxAboveTrig)
  Trigger = FIFOE & RxAboveTrig;


// Interrupt Priority Generation
always @(EnabLnStat or BI or FE or PE or OE or EnabRxBuff or DR or FIFOE or Trigger or
  RTO or EnabTxBuff or THRemI or EnabMdStat or DDCD or TERI or DDSR or DCTS)
begin
  Prior1 = EnabLnStat & (BI | FE | PE | OE);          // RX Error 1st Priority
  Prior2 = EnabRxBuff & ((DR & ~FIFOE) | Trigger);    // Data RX 2nd Priority
  Prior2TO = EnabRxBuff & RTO;                        // Rx FIFO time out 2nd Priority
  Prior3 = EnabTxBuff & THRemI;	                      // TX Buffer empty 3rd Priority
  Prior4 = EnabMdStat & (DDCD | TERI | DDSR | DCTS);  // Modem status line changes 4th Priority
end

// Generate interrupt request
always @(Prior1 or Prior2 or Prior3 or Prior4 or Prior2TO)
  IRQ = Prior1 | Prior2 | Prior3 | Prior4 | Prior2TO;

// Generate interrupt status bits
always @(Prior1 or Prior2 or Prior3 or Prior2TO or Prior4)
begin
  if (Prior1)        IIR = 4'h6;
  else if (Prior2TO) IIR = 4'hC;
  else if (Prior2)   IIR = 4'h4;
  else if (Prior3)   IIR = 4'h2;
  else if (Prior4)   IIR = 4'h0;
  else               IIR = 4'h1;
end

// DMA access pin TXRdy
//
// DMA Mode 0 - Device behaviour is as follows:
//
// Demand transfer - if THR or FIFO written to once
// TXRdy goes inactive (Logic 1), and becomes active
// when the TX SR is empty (TSRE active). If written
// to more than one location TXRdy becomes active when
// the FIFO is empty - i.e. before the TX SR is empty
always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    DMA0_SEL <= 1'b0;
  else if (WrCyc & ADD0)
    DMA0_SEL <= TEmpt;
  else if (WrCyc & ADD2 & ((DataIn[0] ^ FIFOE) | DataIn[2]))
    DMA0_SEL <= 1'b0;
	      
always @(TEmpt or DMA0_SEL or TSRE or FIFOE or THRe)
  if (FIFOE)
  begin
    if (DMA0_SEL)
      DMA0_TXRdy = TSRE;
    else
      DMA0_TXRdy = TEmpt;
  end
  else    
    DMA0_TXRdy = THRe;

// Generate Delta version of DMA0_TXRdy
always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    DMA0_TXRdySamp <= 1'b0;
  else
    DMA0_TXRdySamp <= DMA0_TXRdy;
	   
always @(DMA0_TXRdy or DMA0_TXRdySamp)
  Delta_DMA0_TXRdy = (DMA0_TXRdy & ~DMA0_TXRdySamp);


// If DMA Mode 1 (only possible in 16550A mode) -
// Burst mode transfers - Therefore TXRdy goes 
// inactive when the FIFO is full, and becomes
// active when the FIFO is empty.
always @(FIFOE or DMA or TFull or DMA0_TXRdy)
  if (FIFOE & DMA)
    TXRdy = TFull;
  else
    TXRdy = ~DMA0_TXRdy;

// DMA access pin RXRdy
// As in DMA mode different signals control the
// status of the pin two flip flops are required
// to control it.
always @(FIFOE or DMA or DREmpty or DR)
  if (FIFOE & DMA)
    RXRdy = DREmpty;
  else
    RXRdy = ~DR;

// Create a pulse when positive edge on RTO
always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    RTOSync <= 1'b0;
  else
    RTOSync <= RTO;

always @(RTO or RTOSync)
  RTO_Pulse = RTO & ~RTOSync;


// Create a pulse when positive edge on Trigger
always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    TriggerSync <= 1'b0;
  else
    TriggerSync <= Trigger;

always @(Trigger or TriggerSync)
  Trigger_Pulse = Trigger & ~TriggerSync;

always @(posedge CLOCK or negedge RESETN)
  if (~RESETN)
    DREmptyA <= 1'b0;
  else if (~DMA | RRST)
    DREmptyA <= DREmptyB;
  else if (Trigger_Pulse | RTO_Pulse)	
    DREmptyA <= ~DREmptyB;

always @(posedge CLOCK or negedge RESETN) 
  if (~RESETN)
    DREmptyB <= 1'b0;
  else if (~DMA)
    DREmptyB <= 1'b0;
  else if (RdCyc & ADD0 & RHold)
    DREmptyB <= DREmptyA;

// RXRdy DMA mode flag
always @(DREmptyA or DREmptyB)
  DREmpty = ~(DREmptyA ^ DREmptyB);

endmodule


